event.fee = 0.05
event.page_size=10
booking.page_size=10
booking.payment_timeout_minutes=5
user.page_size=10
jwt.secret=12345678901234567890123456789012



momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.partnerCode=MOMOBKUN20180529
momo.accessKey=klm05TvNBzhg7h7j
momo.secretKey=at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa
momo.partnerName=Test
momo.storeId=MomoTestStore
momo.requestType=captureWallet
momo.lang=vi
#momo.redirectUrl=http://localhost:3000/payment/momo/return
#momo.ipnUrl=http://localhost:8080/SpringEventBookingPlatform/api/payment/momo/ipn

momo.redirectUrl=https://event-booking-platform.pages.dev/payment/momo/return
momo.ipnUrl=https://event-booking-backend-5x8l.onrender.com/api/payment/momo/ipn



mail.enabled=true
mail.host=smtp.gmail.com
mail.port=587
mail.username=thuantokutou@gmail.com
mail.password=fixb bzbd bzrb omau
mail.from=thuantokutou@gmail.com
mail.protocol=smtp
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.timeout=10000
mail.smtp.connectiontimeout=10000
