event.fee = 0.05
event.page_size=10
booking.page_size=10
user.page_size=10
jwt.secret=12345678901234567890123456789012

# Mail notification settings
# Bat true va dien SMTP that khi muon gui email ve sau khi tao booking thanh cong.
mail.enabled=true
mail.host=smtp.gmail.com
mail.port=587
mail.username=thuantokutou@gmail.com
mail.password=fixb bzbd bzrb omau
mail.from=thuantokutou@gmail.com
mail.protocol=smtp
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.timeout=10000
mail.smtp.connectiontimeout=10000
