
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

event.feePerTicket = 2000
event.page_size=10
user.page_size=10
jwt.secret=12345678901234567890123456789012
